language: node_js

sudo: false
dist: trusty
node_js:
   - node

before_script:
   - npm install -g firebase-tools
   - npm install -g --silent @angular/cli

script:
   - ng build --prod

after_success:
   - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
